# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it using the artifactoryPublish task every sunday

name: Artifactory Publish

on:
  schedule:
    - cron: '0 0 * * 0' # every sunday at midnight
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Publish to Artifactory
        uses: gradle/gradle-build-action@v2
        with:
          arguments: artifactoryPublish
        env:
          ORG_GRADLE_PROJECT_artifactory_platform_user: ${{ secrets.ARTIFACTORY_PLATFORM_USER }}
          ORG_GRADLE_PROJECT_artifactory_platform_password: ${{ secrets.ARTIFACTORY_PLATFORM_PASSWORD }}
